// Generated by Skyramp v1.3.12 on 2026-03-12 23:31:49.934321939 +0000 UTC m=+133.786812897
// Command: skyramp generate smoke rest http://localhost:3000/api/v1/collections/1/members/1 \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method DELETE \
// 		--output-dir /home/runner/work/eval-linkwarden/eval-linkwarden/tests \
// 		--overwrite \
// 		--path-params id=1,userId=1 \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// smoke test for /api/v1/collections/1/members/1 DELETE
test('testEndpoint1Delete', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const endpoint1DeleteResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/collections/1/members/1",
        method: "DELETE",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(endpoint1DeleteResponse, "20X"), 'status code').toBeTruthy();
});
