// Generated by Skyramp v1.3.12 on 2026-03-12 23:31:49.889337143 +0000 UTC m=+133.741828111
// Command: skyramp generate smoke rest http://localhost:3000/api/v1/collections/1/members/1 \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method PUT \
// 		--output-dir /home/runner/work/eval-linkwarden/eval-linkwarden/tests \
// 		--overwrite \
// 		--path-params id=1,userId=1 \
// 		--provider \
// 		--request-data {"canCreate":true,"canUpdate":true,"canDelete":false} \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// smoke test for /api/v1/collections/1/members/1 PUT
test('testEndpoint1Put', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const endpoint1PutRequestBody: string = `{
        "canCreate": true,
        "canDelete": false,
        "canUpdate": true
    }`;

    // Execute Request
    const endpoint1PutResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/collections/1/members/1",
        method: "PUT",
        body: endpoint1PutRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(endpoint1PutResponse.statusCode, 'status code').toBe(200);
});
