// Generated by Skyramp v1.3.12 on 2026-03-14 01:15:38.965598254 +0000 UTC m=+133.451896057
// Command: skyramp generate contract rest http://localhost:3000/api/v1/collections \
// 		--auth-header Cookie \
// 		--docker-network eval-linkwarden_default \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime docker \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// contract test for /api/v1/collections GET
test('testCollectionsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient({
        runtime: "docker",
        dockerNetwork: "eval-linkwarden_default",
        dockerSkyrampPort: 35142
    });
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const collectionsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/collections",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(collectionsGetResponse, "20x"), 'status code').toBeTruthy();
});
