// Generated by Skyramp v1.3.14 on 2026-03-20 18:16:28.717988942 +0000 UTC m=+237.362120982
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output collection_member_self_update_blocked.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_collection_member_self_update_blocked.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let collectionsGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/collections",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(collectionsGetResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const membersPutRequestBody = `{
            "canCreate": true,
            "canDelete": true,
            "canUpdate": true
        }`
    
    // Execute Request
    let membersPutResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/collections/{collections}/members/{members}",
        method:"PUT",
        body:membersPutRequestBody,
        headers:headers,
        pathParams:{
            "collections": getResponseValue(collectionsGetResponse, "0.id"),
            "members": getResponseValue(collectionsGetResponse, "0.id")
        }
    });

    // Generated Assertions
    expect(membersPutResponse.statusCode, 'status code').toBe(400);
});

