// Generated by Skyramp v1.3.13 on 2026-03-19 12:17:24.85898613 +0000 UTC m=+133.949752285
// Command: skyramp generate contract rest http://localhost:3000/api/v1/collections/1/members \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_collection_members_get.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--response-data {"response":{"owner":{"id":1,"name":"testuser","username":"testuser","email":"test@example.com","image":null},"members":[{"userId":2,"canCreate":true,"canUpdate":false,"canDelete":false,"user":{"id":2,"name":"member","username":"member","email":"member@example.com","image":null},"createdAt":"2026-03-19T00:00:00.000Z"}]}} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// contract test for /api/v1/collections/1/members GET
test('testMembersGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedMembersGetResponseBody: string = `{
        "response": {
            "members": [
                {
                    "canCreate": true,
                    "canDelete": false,
                    "canUpdate": false,
                    "createdAt": "2026-03-19T00:00:00.000Z",
                    "user": {
                        "email": "member@example.com",
                        "id": 2,
                        "image": null,
                        "name": "member",
                        "username": "member"
                    },
                    "userId": 2
                }
            ],
            "owner": {
                "email": "test@example.com",
                "id": 1,
                "image": null,
                "name": "testuser",
                "username": "testuser"
            }
        }
    }`;

    // Execute Request
    const membersGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/collections/1/members",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(membersGetResponse, "20x"), 'status code').toBeTruthy();
    expect(checkSchema(membersGetResponse, expectedMembersGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(membersGetResponse, "response.members.0.canCreate"), 'value').not.toBeNull();
    expect(getResponseValue(membersGetResponse, "response.members.0.canDelete"), 'value').not.toBeNull();
    expect(getResponseValue(membersGetResponse, "response.members.0.canUpdate"), 'value').not.toBeNull();
});
