// Generated by Skyramp v1.3.13 on 2026-03-16 05:57:01.151576681 +0000 UTC m=+127.435419581
// Command: skyramp generate contract rest http://localhost:3000/api/v1/saved-searches \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_post_saved_searches.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"name":"Contract Test Search 1742094000","description":"Test contract validation","searchQuery":"contract test","sortBy":"createdAt","sortOrder":"desc"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// contract test for /api/v1/saved-searches POST
test('testSavedSearchesPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const savedSearchesPostRequestBody: string = `{
        "description": "Test contract validation",
        "name": "Contract Test Search 1742094000",
        "searchQuery": "contract test",
        "sortBy": "createdAt",
        "sortOrder": "desc"
    }`;

    // Execute Request
    const savedSearchesPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/saved-searches",
        method: "POST",
        body: savedSearchesPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(savedSearchesPostResponse, "20x"), 'status code').toBeTruthy();
});
