// Generated by Skyramp v1.3.13 on 2026-03-16 05:57:00.967763964 +0000 UTC m=+127.251606864
// Command: skyramp generate fuzz rest http://localhost:3000/api/v1/saved-searches \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output fuzz_post_saved_searches.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"name":"Tech Bookmarks","description":"Search for tech bookmarks","searchQuery":"tech","sortBy":"createdAt","sortOrder":"desc"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// fuzz test for /api/v1/saved-searches POST
test('testSavedSearchesPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const savedSearchesPostRequestBody = `{
            "name": "Tech Bookmarks",
            "description": "Search for tech bookmarks",
            "searchQuery": "tech",
            "sortBy": "createdAt",
            "sortOrder": "desc"
        }`
    
    // Fuzz strategies
    const savedSearchesPostFuzzedBody = {
        "description": "0123456789",
        "name": "0123456789",
        "searchQuery": "0123456789",
        "sortBy": "0123456789",
        "sortOrder": "0123456789"
    };
    // Fuzz status codes
    const expectedSavedSearchesPostStatusCode: Record<string, string> = {
        "description": "40x",
        "name": "40x",
        "searchQuery": "40x",
        "sortBy": "40x",
        "sortOrder": "40x"
    };
    // Fuzz status codes for Null values
    const expectedSavedSearchesPostNullStatusCode: Record<string, string> = {
        "description": "40x",
        "name": "40x",
        "searchQuery": "40x",
        "sortBy": "40x",
        "sortOrder": "40x"
    };

    // Execute Request
    let savedSearchesPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/v1/saved-searches",
        method:"POST",
        body:savedSearchesPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(savedSearchesPostFuzzedBody)) {
        // Execute Request
        savedSearchesPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/v1/saved-searches",
            method:"POST",
            body:savedSearchesPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(savedSearchesPostFuzzedBody, key)},
            expectedCode:getValue(expectedSavedSearchesPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(savedSearchesPostFuzzedBody, key)}`
        });


        // Execute Request
        savedSearchesPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/v1/saved-searches",
            method:"POST",
            body:savedSearchesPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedSavedSearchesPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

