// Generated by Skyramp v1.3.13 on 2026-03-19 12:17:21.396320409 +0000 UTC m=+130.487086564
// Command: skyramp generate fuzz rest http://localhost:3000/api/v1/collections/1/members/1 \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method PUT \
// 		--output fuzz_collection_member_permissions.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"canCreate":true,"canUpdate":false,"canDelete":false} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// fuzz test for /api/v1/collections/1/members/1 PUT
test('testEndpoint1Put', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const endpoint1PutRequestBody = `{
            "canCreate": true,
            "canUpdate": false,
            "canDelete": false
        }`
    
    // Fuzz strategies
    const endpoint1PutFuzzedBody = {
        "canCreate": true,
        "canDelete": true,
        "canUpdate": true
    };
    // Fuzz status codes
    const expectedEndpoint1PutStatusCode: Record<string, string> = {
        "canCreate": "40x",
        "canDelete": "40x",
        "canUpdate": "40x"
    };
    // Fuzz status codes for Null values
    const expectedEndpoint1PutNullStatusCode: Record<string, string> = {
        "canCreate": "40x",
        "canDelete": "40x",
        "canUpdate": "40x"
    };

    // Execute Request
    let endpoint1PutResponse = await client.sendRequest({
        url:URL,
        path:"/api/v1/collections/1/members/1",
        method:"PUT",
        body:endpoint1PutRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(endpoint1PutFuzzedBody)) {
        // Execute Request
        endpoint1PutResponse = await client.sendRequest({
            url:URL,
            path:"/api/v1/collections/1/members/1",
            method:"PUT",
            body:endpoint1PutRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(endpoint1PutFuzzedBody, key)},
            expectedCode:getValue(expectedEndpoint1PutStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(endpoint1PutFuzzedBody, key)}`
        });


        // Execute Request
        endpoint1PutResponse = await client.sendRequest({
            url:URL,
            path:"/api/v1/collections/1/members/1",
            method:"PUT",
            body:endpoint1PutRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedEndpoint1PutNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

