// Generated by Skyramp v1.3.13 on 2026-03-17 00:19:47.855197714 +0000 UTC m=+142.637871103
// Command: skyramp generate contract rest http://localhost:3000/api/v1/links/1/notes \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output get_link_notes_contract.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--path-params id=1 \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// contract test for /api/v1/links/1/notes GET
test('testNotesGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const notesGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/links/1/notes",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(notesGetResponse, "20x"), 'status code').toBeTruthy();
});
