// Generated by Skyramp v1.3.13 on 2026-03-16 05:57:51.882788233 +0000 UTC m=+178.166631123
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_saved_searches_crud.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_saved-searches-crud-lifecycle.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const savedSearchesPostRequestBody = `{
            "description": "Search for technology bookmarks",
            "name": "Tech Bookmarks 1742094000",
            "searchQuery": "tech",
            "sortBy": "createdAt",
            "sortOrder": "desc"
        }`
    
    // Execute Request
    let savedSearchesPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches",
        method:"POST",
        body:savedSearchesPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(savedSearchesPostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let savedSearchesSavedSearchesGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches/{saved-searches}",
        method:"GET",
        headers:headers,
        pathParams:{"saved-searches": getResponseValue(savedSearchesPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(savedSearchesSavedSearchesGetResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const savedSearchesSavedSearchesPutRequestBody = `{
            "description": "Updated description for tech bookmarks",
            "name": "Updated Tech Bookmarks 1742094000",
            "searchQuery": "technology news",
            "sortBy": "name",
            "sortOrder": "asc"
        }`
    
    // Execute Request
    let savedSearchesSavedSearchesPutResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches/{saved-searches}",
        method:"PUT",
        body:savedSearchesSavedSearchesPutRequestBody,
        headers:headers,
        pathParams:{"saved-searches": getResponseValue(savedSearchesPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(savedSearchesSavedSearchesPutResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let savedSearchesSavedSearchesDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches/{saved-searches}",
        method:"DELETE",
        headers:headers,
        pathParams:{"saved-searches": getResponseValue(savedSearchesPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(savedSearchesSavedSearchesDeleteResponse.statusCode, 'status code').toBe(200);
});

