// Generated by Skyramp v1.3.13 on 2026-03-19 12:17:18.014932761 +0000 UTC m=+127.105698916
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_collection_members_management.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_collection-members-management.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const collectionsPostRequestBody = `{
            "description": "A collection for member management testing",
            "name": "Shared Collection 1742345678"
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/collections",
        method:"POST",
        body:collectionsPostRequestBody
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let membersGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/collections/{collections}/members",
        method:"GET",
        pathParams:{"collections": getResponseValue(collectionsPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(membersGetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let collectionsCollectionsDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/collections/{collections}",
        method:"DELETE",
        pathParams:{"collections": getResponseValue(collectionsPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(collectionsCollectionsDeleteResponse.statusCode, 'status code').toBe(200);
});

