// Generated by Skyramp v1.3.13 on 2026-03-16 22:40:38.877915641 +0000 UTC m=+148.395323115
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_collection-tag-saved-search-integration.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const collectionsPostRequestBody = `{
            "color": "#0ea5e9",
            "description": "A collection of tech links",
            "name": "Tech Links 20260316"
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/collections",
        method:"POST",
        body:collectionsPostRequestBody
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const tagsPostRequestBody = `{
            "tags": [
                {
                    "label": "technology"
                }
            ]
        }`
    
    // Execute Request
    let tagsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/tags",
        method:"POST",
        body:tagsPostRequestBody
    });

    // Generated Assertions
    expect(tagsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const savedSearchesPostRequestBody = `{
            "collectionId": ${getResponseValue(collectionsPostResponse, "response.id")},
            "description": "Search for tech links",
            "name": "Tech Search 20260316",
            "searchQuery": "technology",
            "sortBy": "createdAt",
            "sortOrder": "desc",
            "tagIds": [
                ${getResponseValue(tagsPostResponse, "response[0].id")}
            ]
        }`
    
    // Execute Request
    let savedSearchesPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches",
        method:"POST",
        body:savedSearchesPostRequestBody
    });

    // Generated Assertions
    expect(savedSearchesPostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let savedSearchesSavedSearchesGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches/{saved-searches}",
        method:"GET",
        pathParams:{"saved-searches": getResponseValue(savedSearchesPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(savedSearchesSavedSearchesGetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let savedSearchesSavedSearchesDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches/{saved-searches}",
        method:"DELETE",
        pathParams:{"saved-searches": getResponseValue(savedSearchesPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(savedSearchesSavedSearchesDeleteResponse.statusCode, 'status code').toBe(200);
});

