// Generated by Skyramp v1.3.14 on 2026-03-20 18:34:26.277658014 +0000 UTC m=+1131.749742952
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_notes_auth_boundary.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_notes-auth-boundary.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const notesPutRequestBody = `{
            "notes": "attempting unauthorized notes update"
        }`
    
    // Execute Request
    let notesPutResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/links/1/notes",
        method:"PUT",
        body:notesPutRequestBody
    });

    // Generated Assertions
    expect(notesPutResponse.statusCode, 'status code').toBe(401);
});

