// Generated by Skyramp v1.3.13 on 2026-03-17 00:43:20.155823984 +0000 UTC m=+188.444862359
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output links_share_full_workflow.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_links-share-full-workflow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const linksPostRequestBody = `{
            "collectionId": 1,
            "description": "A bookmark for testing public link sharing",
            "name": "Shared Bookmark Test",
            "tags": [],
            "url": "https://example.com/shared-bookmark-test"
        }`
    
    // Execute Request
    let linksPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/links",
        method:"POST",
        body:linksPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(linksPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const sharePostRequestBody = `{}`
    
    // Execute Request
    let sharePostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/links/{links}/share",
        method:"POST",
        body:sharePostRequestBody,
        headers:headers,
        pathParams:{"links": getResponseValue(linksPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(sharePostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let shareGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/links/{links}/share",
        method:"GET",
        headers:headers,
        pathParams:{"links": getResponseValue(linksPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(shareGetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let sharedGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/public/shared/{shared}",
        method:"GET",
        headers:headers,
        pathParams:{"shared": getResponseValue(sharePostResponse, "response.shareToken")}
    });

    // Generated Assertions
    expect(sharedGetResponse.statusCode, 'status code').toBe(200);
});

