// Generated by Skyramp v1.3.12 on 2026-03-14 01:15:39.256201054 +0000 UTC m=+133.742498858
// Command: skyramp generate fuzz rest http://localhost:3000/api/v1/links \
// 		--auth-header Cookie \
// 		--docker-network eval-linkwarden_default \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime docker \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// fuzz test for /api/v1/links POST
test('testLinksPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient({
        runtime:"docker",
        dockerNetwork:"eval-linkwarden_default",
        dockerSkyrampPort:35142
    });

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let linksPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/v1/links",
        method:"POST",
        headers:headers,
        expectedCode:"20x"
    });


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

