// Generated by Skyramp v1.3.12 on 2026-03-14 01:15:39.110872278 +0000 UTC m=+133.597170082
// Command: skyramp generate load rest http://localhost:3000/api/v1/links \
// 		--auth-header Cookie \
// 		--default-duration 5 \
// 		--default-num-threads 1 \
// 		--docker-network eval-linkwarden_default \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime docker \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';
import { AsyncScenario, LoadTestConfig } from '@skyramp/skyramp';
// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

let loadTestConfig = new LoadTestConfig({
    loadDuration: 5,
    loadNumThreads: 1
});

test('testLinksGet', async () => {
    test.setTimeout(305000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient({
        runtime:"docker",
        dockerNetwork:"eval-linkwarden_default",
        dockerSkyrampPort:35142
    });

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    const scenario = new AsyncScenario({name: "scenario"});
    // Add Request to Scenario
    let linksGetResponse = scenario.addAsyncRequest({
        name: "links_GET",
        url: URL,
        path: "/api/v1/links",
        method: "GET",
        headers: headers,
        expectedCode: "20x"
    });

    const result = await client.sendScenario(scenario, {
            loadTestConfig: loadTestConfig
        });

    const overallStatus = await result.getOverallStatus();
    console.log(JSON.stringify({ "result": overallStatus }, null, 2));
});

