// Generated by Skyramp v1.3.13 on 2026-03-17 00:19:19.64186014 +0000 UTC m=+114.424533529
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output link_notes_workflow.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_link-notes-workflow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const collectionsPostRequestBody = `{
            "description": "Collection for bookmark notes testing",
            "name": "Notes Test Collection 1742"
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const linksPostRequestBody = `{
            "collection": {
                "id": 1
            },
            "description": "A test bookmark for the notes feature",
            "name": "Test Bookmark for Notes",
            "notes": "Initial notes text for this bookmark",
            "url": "https://example.com/bookmark-notes-test"
        }`
    
    // Execute Request
    let linksPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/links",
        method:"POST",
        body:linksPostRequestBody,
        headers:headers,
        dataOverride:{"collection.id": getResponseValue(collectionsPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(linksPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const notesPutRequestBody = `{
            "notes": "Updated personal annotation - this article is very helpful for research"
        }`
    
    // Execute Request
    let notesPutResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/links/{links}/notes",
        method:"PUT",
        body:notesPutRequestBody,
        headers:headers,
        pathParams:{"links": getResponseValue(linksPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(notesPutResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let notesGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/links/{links}/notes",
        method:"GET",
        headers:headers,
        pathParams:{"links": getResponseValue(linksPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(notesGetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let linksLinksDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/links/{links}",
        method:"DELETE",
        headers:headers,
        pathParams:{"links": getResponseValue(linksPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(linksLinksDeleteResponse.statusCode, 'status code').toBe(200);
});

