// Generated by Skyramp v1.3.12 on 2026-03-12 23:31:32.384363194 +0000 UTC m=+116.236854152
// Command: skyramp generate smoke rest http://localhost:3000/api/v1/collections/1/members \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/eval-linkwarden/eval-linkwarden/tests \
// 		--overwrite \
// 		--path-params id=1 \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// smoke test for /api/v1/collections/1/members GET
test('testMembersGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const membersGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/collections/1/members",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(membersGetResponse.statusCode, 'status code').toBe(200);
});
