// Generated by Skyramp v1.3.13 on 2026-03-17 00:43:30.127519257 +0000 UTC m=+198.416557642
// Command: skyramp generate fuzz rest http://localhost:3000/api/v1/public/shared/invalidtoken \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output public_shared_link_fuzz.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// fuzz test for /api/v1/public/shared/invalidtoken GET
test('testInvalidtokenGet', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let invalidtokenGetResponse = await client.sendRequest({
        url:URL,
        path:"/api/v1/public/shared/invalidtoken",
        method:"GET",
        headers:headers,
        expectedCode:"20x"
    });


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

