// Generated by Skyramp v1.3.13 on 2026-03-17 00:19:56.474530883 +0000 UTC m=+151.257204272
// Command: skyramp generate contract rest http://localhost:3000/api/v1/links/1/notes \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method PUT \
// 		--output put_link_notes_contract.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"notes":"My personal annotation for this bookmark"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// contract test for /api/v1/links/1/notes PUT
test('testNotesPut', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const notesPutRequestBody: string = `{
        "notes": "My personal annotation for this bookmark"
    }`;

    // Execute Request
    const notesPutResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/links/1/notes",
        method: "PUT",
        body: notesPutRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(notesPutResponse, "20x"), 'status code').toBeTruthy();
});
