// Generated by Skyramp v1.3.13 on 2026-03-17 00:19:47.968571118 +0000 UTC m=+142.751244507
// Command: skyramp generate fuzz rest http://localhost:3000/api/v1/links/1/notes \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method PUT \
// 		--output put_link_notes_fuzz.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--path-params id=1 \
// 		--provider \
// 		--request-data {"notes":"Valid annotation text for this bookmark"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// fuzz test for /api/v1/links/1/notes PUT
test('testNotesPut', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const notesPutRequestBody = `{
            "notes": "Valid annotation text for this bookmark"
        }`
    
    // Fuzz strategies
    const notesPutFuzzedBody = {"notes": "0123456789"};
    // Fuzz status codes
    const expectedNotesPutStatusCode: Record<string, string> = {"notes": "40x"};
    // Fuzz status codes for Null values
    const expectedNotesPutNullStatusCode: Record<string, string> = {"notes": "40x"};

    // Execute Request
    let notesPutResponse = await client.sendRequest({
        url:URL,
        path:"/api/v1/links/1/notes",
        method:"PUT",
        body:notesPutRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(notesPutFuzzedBody)) {
        // Execute Request
        notesPutResponse = await client.sendRequest({
            url:URL,
            path:"/api/v1/links/1/notes",
            method:"PUT",
            body:notesPutRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(notesPutFuzzedBody, key)},
            expectedCode:getValue(expectedNotesPutStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(notesPutFuzzedBody, key)}`
        });


        // Execute Request
        notesPutResponse = await client.sendRequest({
            url:URL,
            path:"/api/v1/links/1/notes",
            method:"PUT",
            body:notesPutRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedNotesPutNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

