// Generated by Skyramp v1.3.14 on 2026-03-20 18:17:58.394087732 +0000 UTC m=+193.390637556
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output rss_subscribe_reimport_workflow.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_rss_subscribe_and_reimport_workflow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const importPostRequestBody = `{
            "autoTag": true,
            "collectionName": "RSS Workflow",
            "maxItems": 5,
            "name": "HN Feed",
            "url": "https://hnrss.org/frontpage"
        }`
    
    // Execute Request
    let importPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/rss/import",
        method:"POST",
        body:importPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(importPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const rssImportPostRequestBody = `{
            "autoTag": true,
            "maxItems": 5
        }`
    
    // Execute Request
    let rssImportPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/rss/{rss}/import",
        method:"POST",
        body:rssImportPostRequestBody,
        headers:headers,
        pathParams:{"rss": getResponseValue(importPostResponse, "response.subscription.id")}
    });

    // Generated Assertions
    expect(rssImportPostResponse.statusCode, 'status code').toBe(200);
});

