// Generated by Skyramp v1.3.14 on 2026-03-20 18:17:51.691236581 +0000 UTC m=+186.687786416
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output rss_ownership_enforcement.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_rss_subscription_ownership_enforcement.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const importPostRequestBody = `{
            "autoTag": true,
            "maxItems": 10
        }`
    
    // Execute Request
    let importPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/rss/999999/import",
        method:"POST",
        body:importPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(importPostResponse.statusCode, 'status code').toBe(404);
});

