// Generated by Skyramp v1.3.13 on 2026-03-16 23:52:38.720047644 +0000 UTC m=+225.684275469
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output rss_subscribe_and_import_test.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_rss-subscribe-and-import-1742.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const collectionsPostRequestBody = `{
            "name": "RSS Test Collection 1742"
        }`
    
    // Execute Request
    let collectionsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/collections",
        method:"POST",
        body:collectionsPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(collectionsPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const collectionId1 = getResponseValue(collectionsPostResponse, "response.id");
    const importPostRequestBody = `{
            "autoTag": true,
            "collectionId": ${collectionId1},
            "maxItems": 5,
            "name": "Tech News RSS 1742",
            "url": "https://hnrss.org/frontpage"
        }`
    
    // Execute Request
    let importPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/rss/import",
        method:"POST",
        body:importPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(importPostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let rssDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/rss/{rss}",
        method:"DELETE",
        headers:headers,
        pathParams:{"rss": getResponseValue(importPostResponse, "response.subscription.id")}
    });

    // Generated Assertions
    expect(rssDeleteResponse.statusCode, 'status code').toBe(200);
});

