// Generated by Skyramp v1.3.13 on 2026-03-16 23:51:51.88619485 +0000 UTC m=+178.850422677
// Command: skyramp generate contract rest http://localhost:3000/api/v1/rss/import \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output rss_import_contract_test.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"name":"RSS Contract Test 1742","url":"https://hnrss.org/frontpage","autoTag":true,"maxItems":5} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// contract test for /api/v1/rss/import POST
test('testImportPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const importPostRequestBody: string = `{
        "autoTag": true,
        "maxItems": 5,
        "name": "RSS Contract Test 1742",
        "url": "https://hnrss.org/frontpage"
    }`;

    // Execute Request
    const importPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/rss/import",
        method: "POST",
        body: importPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(importPostResponse, "20x"), 'status code').toBeTruthy();
});
