// Generated by Skyramp v1.3.13 on 2026-03-16 23:51:52.177002423 +0000 UTC m=+179.141230250
// Command: skyramp generate fuzz rest http://localhost:3000/api/v1/rss/import \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output rss_import_fuzz_test.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"name":"RSS Fuzz Test 1742","url":"https://hnrss.org/frontpage","autoTag":true,"maxItems":50} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// fuzz test for /api/v1/rss/import POST
test('testImportPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const importPostRequestBody = `{
            "name": "RSS Fuzz Test 1742",
            "url": "https://hnrss.org/frontpage",
            "autoTag": true,
            "maxItems": 50
        }`
    
    // Fuzz strategies
    const importPostFuzzedBody = {
        "autoTag": true,
        "maxItems": -10,
        "name": "0123456789",
        "url": "0123456789"
    };
    // Fuzz status codes
    const expectedImportPostStatusCode: Record<string, string> = {
        "autoTag": "40x",
        "maxItems": "40x",
        "name": "40x",
        "url": "40x"
    };
    // Fuzz status codes for Null values
    const expectedImportPostNullStatusCode: Record<string, string> = {
        "autoTag": "40x",
        "maxItems": "40x",
        "name": "40x",
        "url": "40x"
    };

    // Execute Request
    let importPostResponse = await client.sendRequest({
        url:URL,
        path:"/api/v1/rss/import",
        method:"POST",
        body:importPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(importPostFuzzedBody)) {
        // Execute Request
        importPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/v1/rss/import",
            method:"POST",
            body:importPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(importPostFuzzedBody, key)},
            expectedCode:getValue(expectedImportPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(importPostFuzzedBody, key)}`
        });


        // Execute Request
        importPostResponse = await client.sendRequest({
            url:URL,
            path:"/api/v1/rss/import",
            method:"POST",
            body:importPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedImportPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

