// Generated by Skyramp v1.3.14 on 2026-03-20 18:12:04.307638287 +0000 UTC m=+168.733181282
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output saved_search_ownership_validation.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_saved_search_ownership_validation.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let savedSearches99999GetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches/99999",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(savedSearches99999GetResponse.statusCode, 'status code').toBe(404);
});

