// Generated by Skyramp v1.3.13 on 2026-03-16 22:41:36.986589483 +0000 UTC m=+206.503996996
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output saved_searches_crud_lifecycle.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_saved-searches-crud-lifecycle.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const savedSearchesPostRequestBody = `{
            "description": "Find all bookmarks",
            "name": "Bookmark Search 20260316",
            "searchQuery": "bookmark",
            "sortBy": "createdAt",
            "sortOrder": "desc"
        }`
    
    // Execute Request
    let savedSearchesPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches",
        method:"POST",
        body:savedSearchesPostRequestBody
    });

    // Generated Assertions
    expect(savedSearchesPostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let savedSearchesGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches",
        method:"GET"
    });

    // Generated Assertions
    expect(savedSearchesGetResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const savedSearchesSavedSearchesPutRequestBody = `{
            "name": "Updated Bookmark Search 20260316",
            "sortOrder": "asc"
        }`
    
    // Execute Request
    let savedSearchesSavedSearchesPutResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches/{saved-searches}",
        method:"PUT",
        body:savedSearchesSavedSearchesPutRequestBody,
        pathParams:{"saved-searches": getResponseValue(savedSearchesPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(savedSearchesSavedSearchesPutResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let savedSearchesSavedSearchesDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches/{saved-searches}",
        method:"DELETE",
        pathParams:{"saved-searches": getResponseValue(savedSearchesPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(savedSearchesSavedSearchesDeleteResponse.statusCode, 'status code').toBe(200);
});

