// Generated by Skyramp v1.3.12 on 2026-03-14 01:16:52.508956283 +0000 UTC m=+116.872520582
// Command: skyramp generate smoke rest http://localhost:3000/api/v1/saved-searches \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"name":"My Test Search","description":"A smoke test saved search","searchQuery":"typescript","sortBy":"createdAt","sortOrder":"desc"} \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// smoke test for /api/v1/saved-searches POST
test('testSavedSearchesPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const savedSearchesPostRequestBody: string = `{
        "description": "A smoke test saved search",
        "name": "My Test Search",
        "searchQuery": "typescript",
        "sortBy": "createdAt",
        "sortOrder": "desc"
    }`;

    // Execute Request
    const savedSearchesPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/saved-searches",
        method: "POST",
        body: savedSearchesPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(savedSearchesPostResponse.statusCode, 'status code').toBe(200);
});
