// Generated by Skyramp v1.3.12 on 2026-03-14 01:16:44.680964092 +0000 UTC m=+109.044528381
// Command: skyramp generate smoke rest http://localhost:3000/api/v1/saved-searches \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// smoke test for /api/v1/saved-searches GET
test('testSavedSearchesGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const savedSearchesGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/saved-searches",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(savedSearchesGetResponse.statusCode, 'status code').toBe(200);
});
