// Generated by Skyramp v1.3.14 on 2026-03-20 18:12:21.556126053 +0000 UTC m=+185.981669028
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output saved_search_list_workflow.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_saved_search_list_workflow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const savedSearchesPostRequestBody = `{
            "name": "List Test Search",
            "searchQuery": "list query",
            "sortBy": "name",
            "sortOrder": "asc"
        }`
    
    // Execute Request
    let savedSearchesPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches",
        method:"POST",
        body:savedSearchesPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(savedSearchesPostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let savedSearchesGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(savedSearchesGetResponse.statusCode, 'status code').toBe(200);
});

