// Generated by Skyramp v1.3.14 on 2026-03-20 18:11:54.131041746 +0000 UTC m=+158.556584731
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output saved_search_duplicate_name.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_saved_search_duplicate_name.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const savedSearchesPostRequestBody = `{
            "name": "Duplicate Name Test",
            "searchQuery": "first search"
        }`
    
    // Execute Request
    let savedSearchesPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches",
        method:"POST",
        body:savedSearchesPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(savedSearchesPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const savedSearchesPost1RequestBody = `{
            "name": "Duplicate Name Test",
            "searchQuery": "second search"
        }`
    
    // Execute Request
    let savedSearchesPost1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/saved-searches",
        method:"POST",
        body:savedSearchesPost1RequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(savedSearchesPost1Response.statusCode, 'status code').toBe(400);
});

