// Generated by Skyramp v1.3.13 on 2026-03-16 22:41:54.380962841 +0000 UTC m=+223.898370311
// Command: skyramp generate contract rest http://localhost:3000/api/v1/saved-searches \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output saved_searches_get_contract.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// contract test for /api/v1/saved-searches GET
test('testSavedSearchesGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const savedSearchesGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/saved-searches",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(savedSearchesGetResponse, "20x"), 'status code').toBeTruthy();
});
