// Generated by Skyramp v1.3.13 on 2026-03-17 00:43:22.285250352 +0000 UTC m=+190.574288717
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output share_revocation_lifecycle.spec.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/linkwarden/linkwarden/tests/scenario_share-revocation-lifecycle.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const linksPostRequestBody = `{
            "collectionId": 1,
            "description": "A bookmark to test share revocation flow",
            "name": "Revocation Test Bookmark",
            "tags": [],
            "url": "https://example.com/revocation-test-bookmark"
        }`
    
    // Execute Request
    let linksPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/links",
        method:"POST",
        body:linksPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(linksPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const sharePostRequestBody = `{}`
    
    // Execute Request
    let sharePostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/links/{links}/share",
        method:"POST",
        body:sharePostRequestBody,
        headers:headers,
        pathParams:{"links": getResponseValue(linksPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(sharePostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let shareDeleteResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/links/{links}/share",
        method:"DELETE",
        headers:headers,
        pathParams:{"links": getResponseValue(linksPostResponse, "response.id")}
    });

    // Generated Assertions
    expect(shareDeleteResponse.statusCode, 'status code').toBe(200);
});

