// Generated by Skyramp v1.3.13 on 2026-03-16 20:27:20.553167982 +0000 UTC m=+77.770622040
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output welcome_banner_ui_test.ts \
// 		--output-dir /home/runner/work/linkwarden/linkwarden/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/linkwarden/linkwarden/tests/welcome_banner_playwright.zip \
// 		--provider \
// 		--skipProvisionParents

// Import of required libraries
import { test } from '@playwright/test';
import { expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(221000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:3000/login");
    await page.getByTestId("username-input").click();
    await page.getByTestId("username-input").fill("test");
    await page.getByTestId("password-input").click();
    await page.getByTestId("password-input").fill("password");
    await page.getByTestId("submit-login-button").click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.locator("#sidebar")).toContainText("Dashboard");
    await page.locator(".inline-flex.items-center.focus\\:outline-none.outline-none.justify-center.gap-2.whitespace-nowrap.text-sm.font-medium.ring-offset-background.duration-150.focus-visible\\:outline-none.disabled\\:pointer-events-none.disabled\\:opacity-50.select-none.hover\\:bg-base-content\\/20.h-10").click();
    await page.getByRole("menuitem", { name: " Server Administration" }).click();
    await expect(page.locator("tbody")).toContainText("test");
});
